get_filename_component(CMAKE_LIBDIR_BASENAME "${CMAKE_INSTALL_LIBDIR}" NAME)

set(CMAKE_BINARY_BINDIR "${CMAKE_BINARY_BINDIR}/bin")
set(CMAKE_BINARY_INCLUDEDIR "${CMAKE_BINARY_DIR}/inc")
set(CMAKE_BINARY_LIBDIR "${CMAKE_BINARY_DIR}/${CMAKE_LIBDIR_BASENAME}")
